/* automatically generated by rust-bindgen 0.71.1 */

#![allow(dead_code, non_camel_case_types, non_snake_case, non_upper_case_globals)]

pub type clingo_literal_t = i32;
pub type clingo_atom_t = u32;
pub type clingo_id_t = u32;
pub type clingo_weight_t = i32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_weighted_literal {
    pub literal: clingo_literal_t,
    pub weight: clingo_weight_t,
}
pub type clingo_weighted_literal_t = clingo_weighted_literal;
pub const clingo_error_e_clingo_error_success: clingo_error_e = 0;
pub const clingo_error_e_clingo_error_runtime: clingo_error_e = 1;
pub const clingo_error_e_clingo_error_logic: clingo_error_e = 2;
pub const clingo_error_e_clingo_error_bad_alloc: clingo_error_e = 3;
pub const clingo_error_e_clingo_error_unknown: clingo_error_e = 4;
pub type clingo_error_e = ::std::os::raw::c_uint;
pub type clingo_error_t = ::std::os::raw::c_int;
pub const clingo_warning_e_clingo_warning_operation_undefined: clingo_warning_e = 0;
pub const clingo_warning_e_clingo_warning_runtime_error: clingo_warning_e = 1;
pub const clingo_warning_e_clingo_warning_atom_undefined: clingo_warning_e = 2;
pub const clingo_warning_e_clingo_warning_file_included: clingo_warning_e = 3;
pub const clingo_warning_e_clingo_warning_variable_unbounded: clingo_warning_e = 4;
pub const clingo_warning_e_clingo_warning_global_variable: clingo_warning_e = 5;
pub const clingo_warning_e_clingo_warning_other: clingo_warning_e = 6;
pub type clingo_warning_e = ::std::os::raw::c_uint;
pub type clingo_warning_t = ::std::os::raw::c_int;
pub type clingo_logger_t = ::std::option::Option<
    unsafe extern "C" fn(
        code: clingo_warning_t,
        message: *const ::std::os::raw::c_char,
        data: *mut ::std::os::raw::c_void,
    ),
>;
pub const clingo_truth_value_e_clingo_truth_value_free: clingo_truth_value_e = 0;
pub const clingo_truth_value_e_clingo_truth_value_true: clingo_truth_value_e = 1;
pub const clingo_truth_value_e_clingo_truth_value_false: clingo_truth_value_e = 2;
pub type clingo_truth_value_e = ::std::os::raw::c_uint;
pub type clingo_truth_value_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_location {
    pub begin_file: *const ::std::os::raw::c_char,
    pub end_file: *const ::std::os::raw::c_char,
    pub begin_line: usize,
    pub end_line: usize,
    pub begin_column: usize,
    pub end_column: usize,
}
pub type clingo_location_t = clingo_location;
pub type clingo_signature_t = u64;
pub const clingo_symbol_type_e_clingo_symbol_type_infimum: clingo_symbol_type_e = 0;
pub const clingo_symbol_type_e_clingo_symbol_type_number: clingo_symbol_type_e = 1;
pub const clingo_symbol_type_e_clingo_symbol_type_string: clingo_symbol_type_e = 4;
pub const clingo_symbol_type_e_clingo_symbol_type_function: clingo_symbol_type_e = 5;
pub const clingo_symbol_type_e_clingo_symbol_type_supremum: clingo_symbol_type_e = 7;
pub type clingo_symbol_type_e = ::std::os::raw::c_uint;
pub type clingo_symbol_type_t = ::std::os::raw::c_int;
pub type clingo_symbol_t = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_symbolic_atoms {
    _unused: [u8; 0],
}
pub type clingo_symbolic_atoms_t = clingo_symbolic_atoms;
pub type clingo_symbolic_atom_iterator_t = u64;
pub type clingo_symbol_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        symbols: *const clingo_symbol_t,
        symbols_size: usize,
        data: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
pub const clingo_theory_term_type_e_clingo_theory_term_type_tuple: clingo_theory_term_type_e = 0;
pub const clingo_theory_term_type_e_clingo_theory_term_type_list: clingo_theory_term_type_e = 1;
pub const clingo_theory_term_type_e_clingo_theory_term_type_set: clingo_theory_term_type_e = 2;
pub const clingo_theory_term_type_e_clingo_theory_term_type_function: clingo_theory_term_type_e = 3;
pub const clingo_theory_term_type_e_clingo_theory_term_type_number: clingo_theory_term_type_e = 4;
pub const clingo_theory_term_type_e_clingo_theory_term_type_symbol: clingo_theory_term_type_e = 5;
pub type clingo_theory_term_type_e = ::std::os::raw::c_uint;
pub type clingo_theory_term_type_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_theory_atoms {
    _unused: [u8; 0],
}
pub type clingo_theory_atoms_t = clingo_theory_atoms;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_assignment {
    _unused: [u8; 0],
}
pub type clingo_assignment_t = clingo_assignment;
pub const clingo_propagator_check_mode_e_clingo_propagator_check_mode_none:
    clingo_propagator_check_mode_e = 0;
pub const clingo_propagator_check_mode_e_clingo_propagator_check_mode_total:
    clingo_propagator_check_mode_e = 1;
pub const clingo_propagator_check_mode_e_clingo_propagator_check_mode_fixpoint:
    clingo_propagator_check_mode_e = 2;
pub const clingo_propagator_check_mode_e_clingo_propagator_check_mode_both:
    clingo_propagator_check_mode_e = 3;
pub type clingo_propagator_check_mode_e = ::std::os::raw::c_uint;
pub type clingo_propagator_check_mode_t = ::std::os::raw::c_int;
pub const clingo_propagator_undo_mode_e_clingo_propagator_undo_mode_default:
    clingo_propagator_undo_mode_e = 0;
pub const clingo_propagator_undo_mode_e_clingo_propagator_undo_mode_always:
    clingo_propagator_undo_mode_e = 1;
pub type clingo_propagator_undo_mode_e = ::std::os::raw::c_uint;
pub type clingo_propagator_undo_mode_t = ::std::os::raw::c_int;
pub const clingo_weight_constraint_type_e_clingo_weight_constraint_type_implication_left:
    clingo_weight_constraint_type_e = -1;
pub const clingo_weight_constraint_type_e_clingo_weight_constraint_type_implication_right:
    clingo_weight_constraint_type_e = 1;
pub const clingo_weight_constraint_type_e_clingo_weight_constraint_type_equivalence:
    clingo_weight_constraint_type_e = 0;
pub type clingo_weight_constraint_type_e = ::std::os::raw::c_int;
pub type clingo_weight_constraint_type_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_propagate_init {
    _unused: [u8; 0],
}
pub type clingo_propagate_init_t = clingo_propagate_init;
pub const clingo_clause_type_e_clingo_clause_type_learnt: clingo_clause_type_e = 0;
pub const clingo_clause_type_e_clingo_clause_type_static: clingo_clause_type_e = 1;
pub const clingo_clause_type_e_clingo_clause_type_volatile: clingo_clause_type_e = 2;
pub const clingo_clause_type_e_clingo_clause_type_volatile_static: clingo_clause_type_e = 3;
pub type clingo_clause_type_e = ::std::os::raw::c_uint;
pub type clingo_clause_type_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_propagate_control {
    _unused: [u8; 0],
}
pub type clingo_propagate_control_t = clingo_propagate_control;
pub type clingo_propagator_init_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut clingo_propagate_init_t,
        arg2: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
pub type clingo_propagator_propagate_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut clingo_propagate_control_t,
        arg2: *const clingo_literal_t,
        arg3: usize,
        arg4: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
pub type clingo_propagator_undo_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const clingo_propagate_control_t,
        arg2: *const clingo_literal_t,
        arg3: usize,
        arg4: *mut ::std::os::raw::c_void,
    ),
>;
pub type clingo_propagator_check_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut clingo_propagate_control_t,
        arg2: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_propagator {
    pub init: ::std::option::Option<
        unsafe extern "C" fn(
            init: *mut clingo_propagate_init_t,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub propagate: ::std::option::Option<
        unsafe extern "C" fn(
            control: *mut clingo_propagate_control_t,
            changes: *const clingo_literal_t,
            size: usize,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub undo: ::std::option::Option<
        unsafe extern "C" fn(
            control: *const clingo_propagate_control_t,
            changes: *const clingo_literal_t,
            size: usize,
            data: *mut ::std::os::raw::c_void,
        ),
    >,
    pub check: ::std::option::Option<
        unsafe extern "C" fn(
            control: *mut clingo_propagate_control_t,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub decide: ::std::option::Option<
        unsafe extern "C" fn(
            thread_id: clingo_id_t,
            assignment: *const clingo_assignment_t,
            fallback: clingo_literal_t,
            data: *mut ::std::os::raw::c_void,
            decision: *mut clingo_literal_t,
        ) -> bool,
    >,
}
pub type clingo_propagator_t = clingo_propagator;
pub const clingo_comment_type_e_clingo_comment_type_line: clingo_comment_type_e = 0;
pub const clingo_comment_type_e_clingo_comment_type_block: clingo_comment_type_e = 1;
pub type clingo_comment_type_e = ::std::os::raw::c_uint;
pub type clingo_comment_type_t = ::std::os::raw::c_int;
pub const clingo_theory_sequence_type_e_clingo_theory_sequence_type_tuple:
    clingo_theory_sequence_type_e = 0;
pub const clingo_theory_sequence_type_e_clingo_theory_sequence_type_set:
    clingo_theory_sequence_type_e = 1;
pub const clingo_theory_sequence_type_e_clingo_theory_sequence_type_list:
    clingo_theory_sequence_type_e = 2;
pub type clingo_theory_sequence_type_e = ::std::os::raw::c_uint;
pub type clingo_theory_sequence_type_t = ::std::os::raw::c_int;
pub const clingo_heuristic_type_e_clingo_heuristic_type_level: clingo_heuristic_type_e = 0;
pub const clingo_heuristic_type_e_clingo_heuristic_type_sign: clingo_heuristic_type_e = 1;
pub const clingo_heuristic_type_e_clingo_heuristic_type_factor: clingo_heuristic_type_e = 2;
pub const clingo_heuristic_type_e_clingo_heuristic_type_init: clingo_heuristic_type_e = 3;
pub const clingo_heuristic_type_e_clingo_heuristic_type_true: clingo_heuristic_type_e = 4;
pub const clingo_heuristic_type_e_clingo_heuristic_type_false: clingo_heuristic_type_e = 5;
pub type clingo_heuristic_type_e = ::std::os::raw::c_uint;
pub type clingo_heuristic_type_t = ::std::os::raw::c_int;
pub const clingo_external_type_e_clingo_external_type_free: clingo_external_type_e = 0;
pub const clingo_external_type_e_clingo_external_type_true: clingo_external_type_e = 1;
pub const clingo_external_type_e_clingo_external_type_false: clingo_external_type_e = 2;
pub const clingo_external_type_e_clingo_external_type_release: clingo_external_type_e = 3;
pub type clingo_external_type_e = ::std::os::raw::c_uint;
pub type clingo_external_type_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_backend {
    _unused: [u8; 0],
}
pub type clingo_backend_t = clingo_backend;
pub const clingo_configuration_type_e_clingo_configuration_type_value: clingo_configuration_type_e =
    1;
pub const clingo_configuration_type_e_clingo_configuration_type_array: clingo_configuration_type_e =
    2;
pub const clingo_configuration_type_e_clingo_configuration_type_map: clingo_configuration_type_e =
    4;
pub type clingo_configuration_type_e = ::std::os::raw::c_uint;
pub type clingo_configuration_type_bitset_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_configuration {
    _unused: [u8; 0],
}
pub type clingo_configuration_t = clingo_configuration;
pub const clingo_statistics_type_e_clingo_statistics_type_empty: clingo_statistics_type_e = 0;
pub const clingo_statistics_type_e_clingo_statistics_type_value: clingo_statistics_type_e = 1;
pub const clingo_statistics_type_e_clingo_statistics_type_array: clingo_statistics_type_e = 2;
pub const clingo_statistics_type_e_clingo_statistics_type_map: clingo_statistics_type_e = 3;
pub type clingo_statistics_type_e = ::std::os::raw::c_uint;
pub type clingo_statistics_type_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_statistic {
    _unused: [u8; 0],
}
pub type clingo_statistics_t = clingo_statistic;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_solve_control {
    _unused: [u8; 0],
}
pub type clingo_solve_control_t = clingo_solve_control;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_model {
    _unused: [u8; 0],
}
pub type clingo_model_t = clingo_model;
pub const clingo_model_type_e_clingo_model_type_stable_model: clingo_model_type_e = 0;
pub const clingo_model_type_e_clingo_model_type_brave_consequences: clingo_model_type_e = 1;
pub const clingo_model_type_e_clingo_model_type_cautious_consequences: clingo_model_type_e = 2;
pub type clingo_model_type_e = ::std::os::raw::c_uint;
pub type clingo_model_type_t = ::std::os::raw::c_int;
pub const clingo_show_type_e_clingo_show_type_shown: clingo_show_type_e = 2;
pub const clingo_show_type_e_clingo_show_type_atoms: clingo_show_type_e = 4;
pub const clingo_show_type_e_clingo_show_type_terms: clingo_show_type_e = 8;
pub const clingo_show_type_e_clingo_show_type_theory: clingo_show_type_e = 16;
pub const clingo_show_type_e_clingo_show_type_all: clingo_show_type_e = 31;
pub const clingo_show_type_e_clingo_show_type_complement: clingo_show_type_e = 32;
pub type clingo_show_type_e = ::std::os::raw::c_uint;
pub type clingo_show_type_bitset_t = ::std::os::raw::c_uint;
pub const clingo_consequence_e_clingo_consequence_false: clingo_consequence_e = 0;
pub const clingo_consequence_e_clingo_consequence_true: clingo_consequence_e = 1;
pub const clingo_consequence_e_clingo_consequence_unknown: clingo_consequence_e = 2;
pub type clingo_consequence_e = ::std::os::raw::c_uint;
pub type clingo_consequence_t = ::std::os::raw::c_int;
pub const clingo_solve_result_e_clingo_solve_result_satisfiable: clingo_solve_result_e = 1;
pub const clingo_solve_result_e_clingo_solve_result_unsatisfiable: clingo_solve_result_e = 2;
pub const clingo_solve_result_e_clingo_solve_result_exhausted: clingo_solve_result_e = 4;
pub const clingo_solve_result_e_clingo_solve_result_interrupted: clingo_solve_result_e = 8;
pub type clingo_solve_result_e = ::std::os::raw::c_uint;
pub type clingo_solve_result_bitset_t = ::std::os::raw::c_uint;
pub const clingo_solve_mode_e_clingo_solve_mode_async: clingo_solve_mode_e = 1;
pub const clingo_solve_mode_e_clingo_solve_mode_yield: clingo_solve_mode_e = 2;
pub type clingo_solve_mode_e = ::std::os::raw::c_uint;
pub type clingo_solve_mode_bitset_t = ::std::os::raw::c_uint;
pub const clingo_solve_event_type_e_clingo_solve_event_type_model: clingo_solve_event_type_e = 0;
pub const clingo_solve_event_type_e_clingo_solve_event_type_unsat: clingo_solve_event_type_e = 1;
pub const clingo_solve_event_type_e_clingo_solve_event_type_statistics: clingo_solve_event_type_e =
    2;
pub const clingo_solve_event_type_e_clingo_solve_event_type_finish: clingo_solve_event_type_e = 3;
pub type clingo_solve_event_type_e = ::std::os::raw::c_uint;
pub type clingo_solve_event_type_t = ::std::os::raw::c_uint;
pub type clingo_solve_event_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        type_: clingo_solve_event_type_t,
        event: *mut ::std::os::raw::c_void,
        data: *mut ::std::os::raw::c_void,
        goon: *mut bool,
    ) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_solve_handle {
    _unused: [u8; 0],
}
pub type clingo_solve_handle_t = clingo_solve_handle;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_ground_program_observer {
    pub init_program: ::std::option::Option<
        unsafe extern "C" fn(incremental: bool, data: *mut ::std::os::raw::c_void) -> bool,
    >,
    pub begin_step:
        ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> bool>,
    pub end_step:
        ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> bool>,
    pub rule: ::std::option::Option<
        unsafe extern "C" fn(
            choice: bool,
            head: *const clingo_atom_t,
            head_size: usize,
            body: *const clingo_literal_t,
            body_size: usize,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub weight_rule: ::std::option::Option<
        unsafe extern "C" fn(
            choice: bool,
            head: *const clingo_atom_t,
            head_size: usize,
            lower_bound: clingo_weight_t,
            body: *const clingo_weighted_literal_t,
            body_size: usize,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub minimize: ::std::option::Option<
        unsafe extern "C" fn(
            priority: clingo_weight_t,
            literals: *const clingo_weighted_literal_t,
            size: usize,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub project: ::std::option::Option<
        unsafe extern "C" fn(
            atoms: *const clingo_atom_t,
            size: usize,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub output_atom: ::std::option::Option<
        unsafe extern "C" fn(
            symbol: clingo_symbol_t,
            atom: clingo_atom_t,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub output_term: ::std::option::Option<
        unsafe extern "C" fn(
            symbol: clingo_symbol_t,
            condition: *const clingo_literal_t,
            size: usize,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub external: ::std::option::Option<
        unsafe extern "C" fn(
            atom: clingo_atom_t,
            type_: clingo_external_type_t,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub assume: ::std::option::Option<
        unsafe extern "C" fn(
            literals: *const clingo_literal_t,
            size: usize,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub heuristic: ::std::option::Option<
        unsafe extern "C" fn(
            atom: clingo_atom_t,
            type_: clingo_heuristic_type_t,
            bias: ::std::os::raw::c_int,
            priority: ::std::os::raw::c_uint,
            condition: *const clingo_literal_t,
            size: usize,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub acyc_edge: ::std::option::Option<
        unsafe extern "C" fn(
            node_u: ::std::os::raw::c_int,
            node_v: ::std::os::raw::c_int,
            condition: *const clingo_literal_t,
            size: usize,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub theory_term_number: ::std::option::Option<
        unsafe extern "C" fn(
            term_id: clingo_id_t,
            number: ::std::os::raw::c_int,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub theory_term_string: ::std::option::Option<
        unsafe extern "C" fn(
            term_id: clingo_id_t,
            name: *const ::std::os::raw::c_char,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub theory_term_compound: ::std::option::Option<
        unsafe extern "C" fn(
            term_id: clingo_id_t,
            name_id_or_type: ::std::os::raw::c_int,
            arguments: *const clingo_id_t,
            size: usize,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub theory_element: ::std::option::Option<
        unsafe extern "C" fn(
            element_id: clingo_id_t,
            terms: *const clingo_id_t,
            terms_size: usize,
            condition: *const clingo_literal_t,
            condition_size: usize,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub theory_atom: ::std::option::Option<
        unsafe extern "C" fn(
            atom_id_or_zero: clingo_id_t,
            term_id: clingo_id_t,
            elements: *const clingo_id_t,
            size: usize,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub theory_atom_with_guard: ::std::option::Option<
        unsafe extern "C" fn(
            atom_id_or_zero: clingo_id_t,
            term_id: clingo_id_t,
            elements: *const clingo_id_t,
            size: usize,
            operator_id: clingo_id_t,
            right_hand_side_id: clingo_id_t,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
}
pub type clingo_ground_program_observer_t = clingo_ground_program_observer;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_part {
    pub name: *const ::std::os::raw::c_char,
    pub params: *const clingo_symbol_t,
    pub size: usize,
}
pub type clingo_part_t = clingo_part;
pub type clingo_ground_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        location: *const clingo_location_t,
        name: *const ::std::os::raw::c_char,
        arguments: *const clingo_symbol_t,
        arguments_size: usize,
        data: *mut ::std::os::raw::c_void,
        symbol_callback: clingo_symbol_callback_t,
        symbol_callback_data: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
pub const clingo_backend_type_e_clingo_backend_type_reify: clingo_backend_type_e = 0;
pub const clingo_backend_type_e_clingo_backend_type_reify_sccs: clingo_backend_type_e = 1;
pub const clingo_backend_type_e_clingo_backend_type_reify_steps: clingo_backend_type_e = 2;
pub const clingo_backend_type_e_clingo_backend_type_aspif: clingo_backend_type_e = 4;
pub const clingo_backend_type_e_clingo_backend_type_smodels: clingo_backend_type_e = 5;
pub type clingo_backend_type_e = ::std::os::raw::c_uint;
pub type clingo_backend_type_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_control {
    _unused: [u8; 0],
}
pub type clingo_control_t = clingo_control;
pub const clingo_ast_theory_sequence_type_e_clingo_ast_theory_sequence_type_tuple:
    clingo_ast_theory_sequence_type_e = 0;
pub const clingo_ast_theory_sequence_type_e_clingo_ast_theory_sequence_type_list:
    clingo_ast_theory_sequence_type_e = 2;
pub const clingo_ast_theory_sequence_type_e_clingo_ast_theory_sequence_type_set:
    clingo_ast_theory_sequence_type_e = 1;
pub type clingo_ast_theory_sequence_type_e = ::std::os::raw::c_uint;
pub type clingo_ast_theory_sequence_type_t = ::std::os::raw::c_int;
pub const clingo_ast_comparison_operator_e_clingo_ast_comparison_operator_greater_than:
    clingo_ast_comparison_operator_e = 0;
pub const clingo_ast_comparison_operator_e_clingo_ast_comparison_operator_less_than:
    clingo_ast_comparison_operator_e = 1;
pub const clingo_ast_comparison_operator_e_clingo_ast_comparison_operator_less_equal:
    clingo_ast_comparison_operator_e = 2;
pub const clingo_ast_comparison_operator_e_clingo_ast_comparison_operator_greater_equal:
    clingo_ast_comparison_operator_e = 3;
pub const clingo_ast_comparison_operator_e_clingo_ast_comparison_operator_not_equal:
    clingo_ast_comparison_operator_e = 4;
pub const clingo_ast_comparison_operator_e_clingo_ast_comparison_operator_equal:
    clingo_ast_comparison_operator_e = 5;
pub type clingo_ast_comparison_operator_e = ::std::os::raw::c_uint;
pub type clingo_ast_comparison_operator_t = ::std::os::raw::c_int;
pub const clingo_ast_sign_e_clingo_ast_sign_no_sign: clingo_ast_sign_e = 0;
pub const clingo_ast_sign_e_clingo_ast_sign_negation: clingo_ast_sign_e = 1;
pub const clingo_ast_sign_e_clingo_ast_sign_double_negation: clingo_ast_sign_e = 2;
pub type clingo_ast_sign_e = ::std::os::raw::c_uint;
pub type clingo_ast_sign_t = ::std::os::raw::c_int;
pub const clingo_ast_unary_operator_e_clingo_ast_unary_operator_minus: clingo_ast_unary_operator_e =
    0;
pub const clingo_ast_unary_operator_e_clingo_ast_unary_operator_negation:
    clingo_ast_unary_operator_e = 1;
pub const clingo_ast_unary_operator_e_clingo_ast_unary_operator_absolute:
    clingo_ast_unary_operator_e = 2;
pub type clingo_ast_unary_operator_e = ::std::os::raw::c_uint;
pub type clingo_ast_unary_operator_t = ::std::os::raw::c_int;
pub const clingo_ast_binary_operator_e_clingo_ast_binary_operator_xor:
    clingo_ast_binary_operator_e = 0;
pub const clingo_ast_binary_operator_e_clingo_ast_binary_operator_or: clingo_ast_binary_operator_e =
    1;
pub const clingo_ast_binary_operator_e_clingo_ast_binary_operator_and:
    clingo_ast_binary_operator_e = 2;
pub const clingo_ast_binary_operator_e_clingo_ast_binary_operator_plus:
    clingo_ast_binary_operator_e = 3;
pub const clingo_ast_binary_operator_e_clingo_ast_binary_operator_minus:
    clingo_ast_binary_operator_e = 4;
pub const clingo_ast_binary_operator_e_clingo_ast_binary_operator_multiplication:
    clingo_ast_binary_operator_e = 5;
pub const clingo_ast_binary_operator_e_clingo_ast_binary_operator_division:
    clingo_ast_binary_operator_e = 6;
pub const clingo_ast_binary_operator_e_clingo_ast_binary_operator_modulo:
    clingo_ast_binary_operator_e = 7;
pub const clingo_ast_binary_operator_e_clingo_ast_binary_operator_power:
    clingo_ast_binary_operator_e = 8;
pub type clingo_ast_binary_operator_e = ::std::os::raw::c_uint;
pub type clingo_ast_binary_operator_t = ::std::os::raw::c_int;
pub const clingo_ast_aggregate_function_e_clingo_ast_aggregate_function_count:
    clingo_ast_aggregate_function_e = 0;
pub const clingo_ast_aggregate_function_e_clingo_ast_aggregate_function_sum:
    clingo_ast_aggregate_function_e = 1;
pub const clingo_ast_aggregate_function_e_clingo_ast_aggregate_function_sump:
    clingo_ast_aggregate_function_e = 2;
pub const clingo_ast_aggregate_function_e_clingo_ast_aggregate_function_min:
    clingo_ast_aggregate_function_e = 3;
pub const clingo_ast_aggregate_function_e_clingo_ast_aggregate_function_max:
    clingo_ast_aggregate_function_e = 4;
pub type clingo_ast_aggregate_function_e = ::std::os::raw::c_uint;
pub type clingo_ast_aggregate_function_t = ::std::os::raw::c_int;
pub const clingo_ast_theory_operator_type_e_clingo_ast_theory_operator_type_unary:
    clingo_ast_theory_operator_type_e = 0;
pub const clingo_ast_theory_operator_type_e_clingo_ast_theory_operator_type_binary_left:
    clingo_ast_theory_operator_type_e = 1;
pub const clingo_ast_theory_operator_type_e_clingo_ast_theory_operator_type_binary_right:
    clingo_ast_theory_operator_type_e = 2;
pub type clingo_ast_theory_operator_type_e = ::std::os::raw::c_uint;
pub type clingo_ast_theory_operator_type_t = ::std::os::raw::c_int;
pub const clingo_ast_theory_atom_definition_type_e_clingo_ast_theory_atom_definition_type_head:
    clingo_ast_theory_atom_definition_type_e = 0;
pub const clingo_ast_theory_atom_definition_type_e_clingo_ast_theory_atom_definition_type_body:
    clingo_ast_theory_atom_definition_type_e = 1;
pub const clingo_ast_theory_atom_definition_type_e_clingo_ast_theory_atom_definition_type_any:
    clingo_ast_theory_atom_definition_type_e = 2;
pub const clingo_ast_theory_atom_definition_type_e_clingo_ast_theory_atom_definition_type_directive : clingo_ast_theory_atom_definition_type_e = 3 ;
pub type clingo_ast_theory_atom_definition_type_e = ::std::os::raw::c_uint;
pub type clingo_ast_theory_atom_definition_type_t = ::std::os::raw::c_int;
pub const clingo_ast_type_e_clingo_ast_type_id: clingo_ast_type_e = 0;
pub const clingo_ast_type_e_clingo_ast_type_variable: clingo_ast_type_e = 1;
pub const clingo_ast_type_e_clingo_ast_type_symbolic_term: clingo_ast_type_e = 2;
pub const clingo_ast_type_e_clingo_ast_type_unary_operation: clingo_ast_type_e = 3;
pub const clingo_ast_type_e_clingo_ast_type_binary_operation: clingo_ast_type_e = 4;
pub const clingo_ast_type_e_clingo_ast_type_interval: clingo_ast_type_e = 5;
pub const clingo_ast_type_e_clingo_ast_type_function: clingo_ast_type_e = 6;
pub const clingo_ast_type_e_clingo_ast_type_pool: clingo_ast_type_e = 7;
pub const clingo_ast_type_e_clingo_ast_type_boolean_constant: clingo_ast_type_e = 8;
pub const clingo_ast_type_e_clingo_ast_type_symbolic_atom: clingo_ast_type_e = 9;
pub const clingo_ast_type_e_clingo_ast_type_comparison: clingo_ast_type_e = 10;
pub const clingo_ast_type_e_clingo_ast_type_guard: clingo_ast_type_e = 11;
pub const clingo_ast_type_e_clingo_ast_type_conditional_literal: clingo_ast_type_e = 12;
pub const clingo_ast_type_e_clingo_ast_type_aggregate: clingo_ast_type_e = 13;
pub const clingo_ast_type_e_clingo_ast_type_body_aggregate_element: clingo_ast_type_e = 14;
pub const clingo_ast_type_e_clingo_ast_type_body_aggregate: clingo_ast_type_e = 15;
pub const clingo_ast_type_e_clingo_ast_type_head_aggregate_element: clingo_ast_type_e = 16;
pub const clingo_ast_type_e_clingo_ast_type_head_aggregate: clingo_ast_type_e = 17;
pub const clingo_ast_type_e_clingo_ast_type_disjunction: clingo_ast_type_e = 18;
pub const clingo_ast_type_e_clingo_ast_type_theory_sequence: clingo_ast_type_e = 19;
pub const clingo_ast_type_e_clingo_ast_type_theory_function: clingo_ast_type_e = 20;
pub const clingo_ast_type_e_clingo_ast_type_theory_unparsed_term_element: clingo_ast_type_e = 21;
pub const clingo_ast_type_e_clingo_ast_type_theory_unparsed_term: clingo_ast_type_e = 22;
pub const clingo_ast_type_e_clingo_ast_type_theory_guard: clingo_ast_type_e = 23;
pub const clingo_ast_type_e_clingo_ast_type_theory_atom_element: clingo_ast_type_e = 24;
pub const clingo_ast_type_e_clingo_ast_type_theory_atom: clingo_ast_type_e = 25;
pub const clingo_ast_type_e_clingo_ast_type_literal: clingo_ast_type_e = 26;
pub const clingo_ast_type_e_clingo_ast_type_theory_operator_definition: clingo_ast_type_e = 27;
pub const clingo_ast_type_e_clingo_ast_type_theory_term_definition: clingo_ast_type_e = 28;
pub const clingo_ast_type_e_clingo_ast_type_theory_guard_definition: clingo_ast_type_e = 29;
pub const clingo_ast_type_e_clingo_ast_type_theory_atom_definition: clingo_ast_type_e = 30;
pub const clingo_ast_type_e_clingo_ast_type_rule: clingo_ast_type_e = 31;
pub const clingo_ast_type_e_clingo_ast_type_definition: clingo_ast_type_e = 32;
pub const clingo_ast_type_e_clingo_ast_type_show_signature: clingo_ast_type_e = 33;
pub const clingo_ast_type_e_clingo_ast_type_show_term: clingo_ast_type_e = 34;
pub const clingo_ast_type_e_clingo_ast_type_minimize: clingo_ast_type_e = 35;
pub const clingo_ast_type_e_clingo_ast_type_script: clingo_ast_type_e = 36;
pub const clingo_ast_type_e_clingo_ast_type_program: clingo_ast_type_e = 37;
pub const clingo_ast_type_e_clingo_ast_type_external: clingo_ast_type_e = 38;
pub const clingo_ast_type_e_clingo_ast_type_edge: clingo_ast_type_e = 39;
pub const clingo_ast_type_e_clingo_ast_type_heuristic: clingo_ast_type_e = 40;
pub const clingo_ast_type_e_clingo_ast_type_project_atom: clingo_ast_type_e = 41;
pub const clingo_ast_type_e_clingo_ast_type_project_signature: clingo_ast_type_e = 42;
pub const clingo_ast_type_e_clingo_ast_type_defined: clingo_ast_type_e = 43;
pub const clingo_ast_type_e_clingo_ast_type_theory_definition: clingo_ast_type_e = 44;
pub const clingo_ast_type_e_clingo_ast_type_comment: clingo_ast_type_e = 45;
pub type clingo_ast_type_e = ::std::os::raw::c_uint;
pub type clingo_ast_type_t = ::std::os::raw::c_int;
pub const clingo_ast_attribute_type_e_clingo_ast_attribute_type_number:
    clingo_ast_attribute_type_e = 0;
pub const clingo_ast_attribute_type_e_clingo_ast_attribute_type_symbol:
    clingo_ast_attribute_type_e = 1;
pub const clingo_ast_attribute_type_e_clingo_ast_attribute_type_location:
    clingo_ast_attribute_type_e = 2;
pub const clingo_ast_attribute_type_e_clingo_ast_attribute_type_string:
    clingo_ast_attribute_type_e = 3;
pub const clingo_ast_attribute_type_e_clingo_ast_attribute_type_ast: clingo_ast_attribute_type_e =
    4;
pub const clingo_ast_attribute_type_e_clingo_ast_attribute_type_optional_ast:
    clingo_ast_attribute_type_e = 5;
pub const clingo_ast_attribute_type_e_clingo_ast_attribute_type_string_array:
    clingo_ast_attribute_type_e = 6;
pub const clingo_ast_attribute_type_e_clingo_ast_attribute_type_ast_array:
    clingo_ast_attribute_type_e = 7;
pub type clingo_ast_attribute_type_e = ::std::os::raw::c_uint;
pub type clingo_ast_attribute_type_t = ::std::os::raw::c_int;
pub const clingo_ast_attribute_e_clingo_ast_attribute_argument: clingo_ast_attribute_e = 0;
pub const clingo_ast_attribute_e_clingo_ast_attribute_arguments: clingo_ast_attribute_e = 1;
pub const clingo_ast_attribute_e_clingo_ast_attribute_arity: clingo_ast_attribute_e = 2;
pub const clingo_ast_attribute_e_clingo_ast_attribute_atom: clingo_ast_attribute_e = 3;
pub const clingo_ast_attribute_e_clingo_ast_attribute_atoms: clingo_ast_attribute_e = 4;
pub const clingo_ast_attribute_e_clingo_ast_attribute_atom_type: clingo_ast_attribute_e = 5;
pub const clingo_ast_attribute_e_clingo_ast_attribute_bias: clingo_ast_attribute_e = 6;
pub const clingo_ast_attribute_e_clingo_ast_attribute_body: clingo_ast_attribute_e = 7;
pub const clingo_ast_attribute_e_clingo_ast_attribute_code: clingo_ast_attribute_e = 8;
pub const clingo_ast_attribute_e_clingo_ast_attribute_coefficient: clingo_ast_attribute_e = 9;
pub const clingo_ast_attribute_e_clingo_ast_attribute_comparison: clingo_ast_attribute_e = 10;
pub const clingo_ast_attribute_e_clingo_ast_attribute_condition: clingo_ast_attribute_e = 11;
pub const clingo_ast_attribute_e_clingo_ast_attribute_elements: clingo_ast_attribute_e = 12;
pub const clingo_ast_attribute_e_clingo_ast_attribute_external: clingo_ast_attribute_e = 13;
pub const clingo_ast_attribute_e_clingo_ast_attribute_external_type: clingo_ast_attribute_e = 14;
pub const clingo_ast_attribute_e_clingo_ast_attribute_function: clingo_ast_attribute_e = 15;
pub const clingo_ast_attribute_e_clingo_ast_attribute_guard: clingo_ast_attribute_e = 16;
pub const clingo_ast_attribute_e_clingo_ast_attribute_guards: clingo_ast_attribute_e = 17;
pub const clingo_ast_attribute_e_clingo_ast_attribute_head: clingo_ast_attribute_e = 18;
pub const clingo_ast_attribute_e_clingo_ast_attribute_is_default: clingo_ast_attribute_e = 19;
pub const clingo_ast_attribute_e_clingo_ast_attribute_left: clingo_ast_attribute_e = 20;
pub const clingo_ast_attribute_e_clingo_ast_attribute_left_guard: clingo_ast_attribute_e = 21;
pub const clingo_ast_attribute_e_clingo_ast_attribute_literal: clingo_ast_attribute_e = 22;
pub const clingo_ast_attribute_e_clingo_ast_attribute_location: clingo_ast_attribute_e = 23;
pub const clingo_ast_attribute_e_clingo_ast_attribute_modifier: clingo_ast_attribute_e = 24;
pub const clingo_ast_attribute_e_clingo_ast_attribute_name: clingo_ast_attribute_e = 25;
pub const clingo_ast_attribute_e_clingo_ast_attribute_node_u: clingo_ast_attribute_e = 26;
pub const clingo_ast_attribute_e_clingo_ast_attribute_node_v: clingo_ast_attribute_e = 27;
pub const clingo_ast_attribute_e_clingo_ast_attribute_operator_name: clingo_ast_attribute_e = 28;
pub const clingo_ast_attribute_e_clingo_ast_attribute_operator_type: clingo_ast_attribute_e = 29;
pub const clingo_ast_attribute_e_clingo_ast_attribute_operators: clingo_ast_attribute_e = 30;
pub const clingo_ast_attribute_e_clingo_ast_attribute_parameters: clingo_ast_attribute_e = 31;
pub const clingo_ast_attribute_e_clingo_ast_attribute_positive: clingo_ast_attribute_e = 32;
pub const clingo_ast_attribute_e_clingo_ast_attribute_priority: clingo_ast_attribute_e = 33;
pub const clingo_ast_attribute_e_clingo_ast_attribute_right: clingo_ast_attribute_e = 34;
pub const clingo_ast_attribute_e_clingo_ast_attribute_right_guard: clingo_ast_attribute_e = 35;
pub const clingo_ast_attribute_e_clingo_ast_attribute_sequence_type: clingo_ast_attribute_e = 36;
pub const clingo_ast_attribute_e_clingo_ast_attribute_sign: clingo_ast_attribute_e = 37;
pub const clingo_ast_attribute_e_clingo_ast_attribute_symbol: clingo_ast_attribute_e = 38;
pub const clingo_ast_attribute_e_clingo_ast_attribute_term: clingo_ast_attribute_e = 39;
pub const clingo_ast_attribute_e_clingo_ast_attribute_terms: clingo_ast_attribute_e = 40;
pub const clingo_ast_attribute_e_clingo_ast_attribute_value: clingo_ast_attribute_e = 41;
pub const clingo_ast_attribute_e_clingo_ast_attribute_variable: clingo_ast_attribute_e = 42;
pub const clingo_ast_attribute_e_clingo_ast_attribute_weight: clingo_ast_attribute_e = 43;
pub const clingo_ast_attribute_e_clingo_ast_attribute_comment_type: clingo_ast_attribute_e = 44;
pub type clingo_ast_attribute_e = ::std::os::raw::c_uint;
pub type clingo_ast_attribute_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_ast_attribute_names {
    pub names: *const *const ::std::os::raw::c_char,
    pub size: usize,
}
pub type clingo_ast_attribute_names_t = clingo_ast_attribute_names;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_ast_argument {
    pub attribute: clingo_ast_attribute_t,
    pub type_: clingo_ast_attribute_type_t,
}
pub type clingo_ast_argument_t = clingo_ast_argument;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_ast_constructor {
    pub name: *const ::std::os::raw::c_char,
    pub arguments: *const clingo_ast_argument_t,
    pub size: usize,
}
pub type clingo_ast_constructor_t = clingo_ast_constructor;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_ast_constructors {
    pub constructors: *const clingo_ast_constructor_t,
    pub size: usize,
}
pub type clingo_ast_constructors_t = clingo_ast_constructors;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_ast {
    _unused: [u8; 0],
}
pub type clingo_ast_t = clingo_ast;
pub type clingo_ast_callback_t = ::std::option::Option<
    unsafe extern "C" fn(ast: *mut clingo_ast_t, data: *mut ::std::os::raw::c_void) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_program_builder {
    _unused: [u8; 0],
}
pub type clingo_program_builder_t = clingo_program_builder;
pub const clingo_ast_unpool_type_e_clingo_ast_unpool_type_condition: clingo_ast_unpool_type_e = 1;
pub const clingo_ast_unpool_type_e_clingo_ast_unpool_type_other: clingo_ast_unpool_type_e = 2;
pub const clingo_ast_unpool_type_e_clingo_ast_unpool_type_all: clingo_ast_unpool_type_e = 3;
pub type clingo_ast_unpool_type_e = ::std::os::raw::c_uint;
pub type clingo_ast_unpool_type_bitset_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_options {
    _unused: [u8; 0],
}
pub type clingo_options_t = clingo_options;
pub type clingo_main_function_t = ::std::option::Option<
    unsafe extern "C" fn(
        control: *mut clingo_control_t,
        files: *const *const ::std::os::raw::c_char,
        size: usize,
        data: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
pub type clingo_default_model_printer_t =
    ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> bool>;
pub type clingo_model_printer_t = ::std::option::Option<
    unsafe extern "C" fn(
        model: *const clingo_model_t,
        printer: clingo_default_model_printer_t,
        printer_data: *mut ::std::os::raw::c_void,
        data: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_application {
    pub program_name: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> *const ::std::os::raw::c_char,
    >,
    pub version: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> *const ::std::os::raw::c_char,
    >,
    pub message_limit: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_uint,
    >,
    pub main: clingo_main_function_t,
    pub logger: clingo_logger_t,
    pub printer: clingo_model_printer_t,
    pub register_options: ::std::option::Option<
        unsafe extern "C" fn(
            options: *mut clingo_options_t,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub validate_options:
        ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> bool>,
}
pub type clingo_application_t = clingo_application;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct clingo_script {
    pub execute: ::std::option::Option<
        unsafe extern "C" fn(
            location: *const clingo_location_t,
            code: *const ::std::os::raw::c_char,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub call: ::std::option::Option<
        unsafe extern "C" fn(
            location: *const clingo_location_t,
            name: *const ::std::os::raw::c_char,
            arguments: *const clingo_symbol_t,
            arguments_size: usize,
            symbol_callback: clingo_symbol_callback_t,
            symbol_callback_data: *mut ::std::os::raw::c_void,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub callable: ::std::option::Option<
        unsafe extern "C" fn(
            name: *const ::std::os::raw::c_char,
            result: *mut bool,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub main: ::std::option::Option<
        unsafe extern "C" fn(
            control: *mut clingo_control_t,
            data: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub free: ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void)>,
    pub version: *const ::std::os::raw::c_char,
}
pub type clingo_script_t = clingo_script;
